@startuml

!if %variable_exists("$THEME")
title 阿里巴巴分层应用架构时序图 - $THEME theme
!else
title 阿里巴巴分层应用架构时序图
!endif

'skinparam BackgroundColor transparent

autonumber
participant "主动适配器" #SkyBlue
participant "eden-demo-layer-web" #LightGreen
participant "eden-demo-layer-service" #LightGreen
participant "eden-demo-layer-manager" #LightGreen
participant "eden-demo-layer-dao" #LightGreen
participant "被动驱动器" #Pink
participant "扩展点" #Khaki

== 场景一：HTTP更新数据请求 ==

"主动适配器" -> "eden-demo-layer-web": 发送写请求报文
"eden-demo-layer-web" -> "eden-demo-layer-service": 进程内请求分发
"eden-demo-layer-service" -> "eden-demo-layer-dao": 调用数据访问层
"eden-demo-layer-service" -> "eden-demo-layer-manager": 调用已编排的业务（可选）
"eden-demo-layer-manager" -> "eden-demo-layer-dao": 调用DAO（可选）
"eden-demo-layer-manager" -> "被动驱动器": 封装第三方中间件SDK，缓存、MQ、定时任务
"eden-demo-layer-dao" -> "被动驱动器": 调用底层组件进行写操作
"eden-demo-layer-dao" --> "eden-demo-layer-service": 返回查询数据
"eden-demo-layer-service" --> "eden-demo-layer-web": 组装返回数据
"eden-demo-layer-web" --> "主动适配器": 响应报文

== 场景二：HTTP查询数据请求 ==

"主动适配器" -> "eden-demo-layer-web": 发送读请求报文
"eden-demo-layer-web" -> "eden-demo-layer-service": 进程内请求分发
"eden-demo-layer-service" -> "eden-demo-layer-dao": 调用数据访问层
"eden-demo-layer-service" -> "eden-demo-layer-manager": 调用已编排的业务（可选）
"eden-demo-layer-manager" -> "eden-demo-layer-dao": 调用DAO（可选）
"eden-demo-layer-manager" -> "被动驱动器": 封装第三方中间件SDK，缓存、MQ、定时任务
"eden-demo-layer-dao" -> "被动驱动器": 调用底层组件进行读操作
"eden-demo-layer-dao" --> "eden-demo-layer-service": 返回查询数据
"eden-demo-layer-service" --> "eden-demo-layer-web": 组装返回数据
"eden-demo-layer-web" --> "主动适配器": 响应报文

== 场景三：MQ消息驱动/Job定时任务触发 ==

"主动适配器" -> "eden-demo-layer-manager": 监听事件触发

alt#Gold #LightBlue 更新操作
	"eden-demo-layer-manager" -> "eden-demo-layer-dao": 更新数据库
	"eden-demo-layer-dao" -> "被动驱动器": 调用底层组件进行写操作
	"eden-demo-layer-dao" --> "eden-demo-layer-manager": 返回数据更新结果
else #Pink 查询操作
	"eden-demo-layer-manager" -> "eden-demo-layer-dao": 查询数据库
	"eden-demo-layer-dao" -> "被动驱动器": 调用底层组件进行读操作
	"eden-demo-layer-dao" --> "eden-demo-layer-manager": 返回数据查询数据
end
"eden-demo-layer-manager" -> "eden-demo-layer-manager": 内部处理（ACK确认/Status状态）
"eden-demo-layer-manager" --> "主动适配器": 处理结果上报

@enduml
